CREATE TABLE users ( 
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username VARCHAR ( 50 ) UNIQUE NOT NULL,
  email VARCHAR ( 50 ) UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  salt VARCHAR NOT NULL,
  full_name VARCHAR ( 100 ),
  bio VARCHAR ( 255 ),
  last_login TIMESTAMP,
  created_on TIMESTAMP DEFAULT NOW() NOT NULL
);
